### ISSUE TITLE
Tram disappearing

### ISSUE THREAD

**Issue by chad50001** [VenomXNL/XNL-FiveM-Trains-U3#15] opened 2024-12-18 14:53 UTC
When the tram reaches the point shown on the image it disappears. idk why.
![image](https://github.com/user-attachments/assets/89156d59-cf32-418a-afff-1f84346296c5)

**Comment by VenomXNL** [comment] 2024-12-18 15:04
Sorry man, there is nothing I can do about that. You could however check if there are any other scripts that interfere with the trains (or traffic/population (density) in general).

However the script I've published has been updated few months ago and it basically doesn't handle controlling the trains at all anymore. It does now just activate the native game train systems and certain tracks of it, after that it's basically all "In the hands of Rockstar/FiveM" so to speak.

Literally all it is doing these days (aside from the ticket stuff of course 😉):
`	SwitchTrainTrack(0, true) 					-- Main train track(s) around LS and towards Sandy Shores 
	SwitchTrainTrack(3, true) 					-- Metro tracks 
	-- NOTE: You can lower the 120000 numbers bellow to make the trains spawn more often, but this is NOT recommended!
	SetTrainTrackSpawnFrequency(0, 120000)		-- The Train spawn frequency set for the game engine 
	SetTrainTrackSpawnFrequency(3, 120000)		-- The Metro spawn frequency set for the game engine 
	SetRandomTrains(true)						-- Telling the game we want to use randomly spawned trains end)
`

So I will close the issue, since it's not an issue related to, caused by or solvable by my script (hope you understand) 😊

**Closed as completed by VenomXNL** 2024-12-18 15:04 UTC
